### ISSUE TITLE
Translate French

### ISSUE THREAD

**Issue by Felixlechatt** [trollix/home-assistant-sun-card#1]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hello, 
in french the "midi solaire" is "Zenith".
You can change this world translate to "Zenith" for more short and must good french :)

Thx

### Describe the solution you'd like

Change in translate french this word "midi solaire" to "Zenith"

### Describe alternatives you've considered

Change in translate french this word "midi solaire" to "Zenith"

### Additional context

Is most french for all population french 👍

**Comment by trollix** [comment]
Hello,
it's ok in 0.72.5 version. Thanks for help.
