### ISSUE TITLE
Latest version isn't working

### ISSUE THREAD

**Issue by ShonP40** [trollix/home-assistant-sun-card#2]
## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4726
Installed Version | 1.33.0
Stage | running
Available Repositories | 1315
Downloaded Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.7 GB
disk_used | 37.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 16
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 7, 2023 at 1:29 AM
-- | --
current_recorder_run | October 17, 2023 at 6:05 PM
estimated_db_size | 2795.42 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The sun card does no longer load after updating to the latest version.

![image](https://github.com/trollix/home-assistant-sun-card/assets/13995143/918900e7-c384-42f6-914e-b82cbd5676fe)

(0.72.9 works fine tho)

### Reproduction steps

1. Install the latest version of this card (0.72.11)
2. Attempt to add the card to the UI
3. Experience error

### Debug logs

```text
- Uncaught error from Safari 17.0 on Mac OS 10.15.7 TypeError: e.constructor.createProperty is not a function. (In 'e.constructor.createProperty(o,r?{...t,wrapped:!0}:t)', 'e.constructor.createProperty' is undefined) /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:608:708 decorateElement (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:327:84) /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:297:58 forEach ([native code]::) decorateClass (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:295:23) _decorate (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:240:36) module code (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:1136:24)

- Uncaught error from Chrome WebView 117.0.0.0 on Android 13 TypeError: e.constructor.createProperty is not a function /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:608:694 /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:608:781 Object.decorateElement (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:327:84) Object.<anonymous> (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:297:43) Object.decorateClass (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:295:16) _decorate (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:240:23) /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:1136:15

- Uncaught error from WebKit 605.1.15 on iOS 17.1 TypeError: e.constructor.createProperty is not a function. (In 'e.constructor.createProperty(o,r?{...t,wrapped:!0}:t)', 'e.constructor.createProperty' is undefined) /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:608:708 decorateElement (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:327:84) /hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:297:58 forEach ([native code]::) decorateClass (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:295:23) _decorate (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:240:36) module code (/hacsfiles/home-assistant-sun-card/home-assistant-sun-card2.js:1136:24)
```

**Comment by trollix** [comment]
Hello,
Thanks for the report.
It's ok with the latest version.

**Comment by ShonP40** [comment]
Thank you, it's working now
